### ISSUE TITLE
Barlseepra under enhancing causes an unhandled excepction as whm/sch

### ISSUE THREAD

**Issue by MLZ333** [DanielHazzard/Cure-Please#105]
System.NullReferenceException: Object reference not set to an instance of an object.
   at CurePlease.Form1.DetermineTierSpells()
   at CurePlease.Form1.<actionTimer_TickAsync>d__186.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by DanielHazzard** [comment]
I'll look into it, Thank you for the report.

**Comment by MLZ333** [comment]
Good luck! Thanks for the reply.
