### ISSUE TITLE
net framework error

### ISSUE THREAD

**Issue by Ba1dw1n** [DanielHazzard/Cure-Please#22]
Hello, first of all thanks for your great work.
With the latest release (2.0.3.0 i am getting the following net framework error.  i did not get this error with 2.0.2.9. everything seems to still run when i get the error though, i am using the exact same settings that i did with 2.0.2.9
************** Exception Text **************
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at CurePlease.PartyBuffs.update_effects_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by DanielHazzard** [comment]
Is this while viewing the PartyBuffs window?

**Comment by Ba1dw1n** [comment]
No,  I don't have that opened. I tried to pin it down on a certain spell or ability and it seems random. I reverted back to 2.0.9 and reverted back to that versions addon and the error is gone.
