### ISSUE TITLE
Crashes when  loading or saving settings

### ISSUE THREAD

**Issue by Muff-top** [DanielHazzard/Cure-Please#99]
Crashes when  loading or saving settings

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CurePlease.Form1.DetermineTierSpells()
   at CurePlease.Form1.<actionTimer_TickAsync>d__186.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by DanielHazzard** [comment]
Pushed a fix.

**Comment by jmhgit** [comment]
i get the same error. just posted a bug. you should check to see if you are trying to use barsleepra. also, once it crashes once you need to quit and restart the application, because even if you untic the barsleepra spell its still busted til the application restarts.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CurePlease.Form1.DetermineTierSpells()
   at CurePlease.Form1.<actionTimer_TickAsync>d__186.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by Muff-top** [comment]
The exception disappeared after i restarted windower and my PC. Program is running normally for now. I don't remember if I had barsleepra on. I might have.
